#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
set -v

# Installs this vim configuration in the current user's linux machine.

VIMDIR="$PWD"

cd "$VIMDIR/.."
ln -i -s "$VIMDIR/vimrc" ".vimrc"

cd "$VIMDIR/.."
mkdir -p "$HOME/.config"
cd "$HOME/.config"
ln -i -s "$VIMDIR" "$HOME/.config/nvim"

cd "$VIMDIR"
git submodule update --init
